from src.eda.univariate_analysis.cancellation_rates import plot_cancellation_metrics
from src.eda.univariate_analysis.market_segments_analysis import plot_marketing_segments_insights
from src.eda.univariate_analysis.repeated_gusests_analysis import plot_returning_customer_analysis
from src.eda.univariate_analysis.revenue_analysis import plot_revenue_optimization_metrics
